#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Client
#        - App\Entity\Station
#        - App\Entity\Operateur
#        - App\Entity\Consommation
#        - App\Entity\Operateur
#        - App\Entity\Facture